export const THEMES = {
  'midnight-command': {
    name: 'Midnight Command',
    emoji: '🌌',
    preview: '#60a5fa',
    vars: {
      '--bg-base':      '#0f1623',
      '--bg-surface':   '#111c2d',
      '--bg-elevated':  '#162236',
      '--bg-border':    '#1e2d45',
      '--accent':       '#60a5fa',
      '--accent-dim':   '#1e3a5f',
      '--accent-text':  '#042c53',
      '--text-primary':   '#e2e8f0',
      '--text-secondary': '#94a3b8',
      '--text-muted':     '#64748b',
      '--text-disabled':  '#4a5568',
      '--danger':       '#ef4444',
      '--danger-dim':   '#2a1a1a',
      '--success':      '#22c55e',
      '--success-dim':  '#0a2e1a',
    },
  },
  'carbon-amber': {
    name: 'Carbon & Amber',
    emoji: '🔥',
    preview: '#f59e0b',
    vars: {
      '--bg-base':      '#111111',
      '--bg-surface':   '#1a1a1a',
      '--bg-elevated':  '#242424',
      '--bg-border':    '#2a2a2a',
      '--accent':       '#f59e0b',
      '--accent-dim':   '#2a1f00',
      '--accent-text':  '#1a1200',
      '--text-primary':   '#f5f5f5',
      '--text-secondary': '#a3a3a3',
      '--text-muted':     '#737373',
      '--text-disabled':  '#525252',
      '--danger':       '#ef4444',
      '--danger-dim':   '#2a1a1a',
      '--success':      '#22c55e',
      '--success-dim':  '#0a2e1a',
    },
  },
  'slate-emerald': {
    name: 'Slate & Emerald',
    emoji: '🌿',
    preview: '#10b981',
    vars: {
      '--bg-base':      '#131920',
      '--bg-surface':   '#1a2330',
      '--bg-elevated':  '#1f2a3a',
      '--bg-border':    '#243040',
      '--accent':       '#10b981',
      '--accent-dim':   '#0d2e22',
      '--accent-text':  '#052e1c',
      '--text-primary':   '#e2e8f0',
      '--text-secondary': '#94a3b8',
      '--text-muted':     '#64748b',
      '--text-disabled':  '#4a5568',
      '--danger':       '#ef4444',
      '--danger-dim':   '#2a1a1a',
      '--success':      '#10b981',
      '--success-dim':  '#0d2e22',
    },
  },
  'frost': {
    name: 'Frost',
    emoji: '❄️',
    preview: '#185fa5',
    vars: {
      '--bg-base':      '#f8fafc',
      '--bg-surface':   '#ffffff',
      '--bg-elevated':  '#f1f5f9',
      '--bg-border':    '#e2e8f0',
      '--accent':       '#185fa5',
      '--accent-dim':   '#e6f1fb',
      '--accent-text':  '#042c53',
      '--text-primary':   '#1e293b',
      '--text-secondary': '#64748b',
      '--text-muted':     '#94a3b8',
      '--text-disabled':  '#cbd5e1',
      '--danger':       '#dc2626',
      '--danger-dim':   '#fef2f2',
      '--success':      '#16a34a',
      '--success-dim':  '#f0fdf4',
    },
  },
  'graphite-gold': {
    name: 'Graphite & Gold',
    emoji: '✨',
    preview: '#d4a017',
    vars: {
      '--bg-base':      '#1a1a1a',
      '--bg-surface':   '#242424',
      '--bg-elevated':  '#2e2e2e',
      '--bg-border':    '#333333',
      '--accent':       '#d4a017',
      '--accent-dim':   '#2e2600',
      '--accent-text':  '#1a1200',
      '--text-primary':   '#f5f5f5',
      '--text-secondary': '#999999',
      '--text-muted':     '#777777',
      '--text-disabled':  '#555555',
      '--danger':       '#ef4444',
      '--danger-dim':   '#2a1a1a',
      '--success':      '#22c55e',
      '--success-dim':  '#0a2e1a',
    },
  },
};
